# Generated by Django 4.0.5 on 2022-06-11 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0004_questionoption")]

    operations = [
        migrations.CreateModel(
            name="QuizParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("ACTIVE", "Active"),
                            ("FINISHED", "Finished"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="NOT_STARTED",
                        max_length=11,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participations",
                        to="core.question",
                    ),
                ),
            ],
        )
    ]
